runtime: nodejs10

instance_class: B2

basic_scaling:
  max_instances: 10

env_variables:
  BUCKET_NAME: "example-bucket"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto